from scipy.stats import spearmanr
import json
import numpy as np
import argparse
import matplotlib.pyplot as plt

"""
In order to get the correct results from this script, you need to include GSL results in your scripts.
To do this, un-comment the block quote in `parse_ingress_traffic_by_satellite.py` and generate a separate
ingress traffic file to use with this script.

THIS SCRIPT ASSUMES 100 MS UPDATES FOR HYPATIA and 200s simulation.

ingress_with_gs_filename: the previously generated file
centrality_directory: the directory for the betweenness_centrality files,
generated by `parse_betweenness_centrality.py`
num_satellites: the number of satellites being tested
averaging_over_timestamps_n: the number of timestamps of data to average over (recommend >=10)
visualization_timestamp_s: when generating the ingress/centrality plot, this argument relates to the timestamp for ingress/centrality data

example command: python3 plot_centrality_ingress_correlation.py <path to ingress file> <path to directory for betweenness_centrality files> 1584 10 160
"""
parser = argparse.ArgumentParser()
parser.add_argument("ingress_with_gs_filename")
parser.add_argument("centrality_directory")
parser.add_argument("num_satellites", type=int)
parser.add_argument("averaging_over_timestamps_n", type=int)
parser.add_argument("visualization_timestamp_s", type=int)
args = parser.parse_args()

simulation_length_s = 200
interval_s = 0.1

averaged_data_length = int(
    (simulation_length_s / interval_s) / args.averaging_over_timestamps_n
)

ingress_list = np.zeros((args.num_satellites, averaged_data_length))
centrality_list = np.zeros((args.num_satellites, averaged_data_length))

ingress_data_in_memory = {}

with open(args.ingress_with_gs_filename) as f:
    ingress_data_in_memory = json.load(f)

for index in range(int(simulation_length_s / interval_s)):
    """
    read the ingress file into a dictionary, keyed by timestamp 
    """
    ingress_moment = ingress_data_in_memory[f"{index}"]
    for key in ingress_moment.keys():
        ingress_list[int(key), int(index / args.averaging_over_timestamps_n)] += int(
            ingress_moment[key]
        )

    """
    read the centrality files into a dictionary, keyed by timestamp 
    """

    with open(
        f"{args.centrality_directory}/betweenness_centrality_{int(index * interval_s * 1_000_000_000)}.json",
        "r",
    ) as f:
        centrality_moment = json.load(f)
        for key in centrality_moment.keys():
            centrality_list[
                int(key), int(index / args.averaging_over_timestamps_n)
            ] += int(centrality_moment[key])

combined_centrality_ingress = [
    [(ingress_list[k, i], centrality_list[k, i]) for k in range(args.num_satellites)]
    for i in range(averaged_data_length)
]

"""
Plot spearman coefficient over all time
"""
rhos = []
ps = []
for timestep in range(averaged_data_length):
    rho, p = spearmanr(
        [i[0] for i in combined_centrality_ingress[timestep]],
        [i[1] for i in combined_centrality_ingress[timestep]],
    )
    rhos.append(rho)
    ps.append(p)

fig, ax = plt.subplots(1, 1)
ax.plot(
    [
        i * (interval_s * args.averaging_over_timestamps_n)
        for i in range(
            int(simulation_length_s / (interval_s * args.averaging_over_timestamps_n))
        )
    ],
    rhos,
)
ax.set_xlabel("Time (s)")
ax.set_ylabel("Spearman Coefficient")
ax.set_title(
    f"Spearman Coefficient Over Time \n Averaged Over {args.averaging_over_timestamps_n * interval_s} s Intervals"
)
plt.savefig("spearman_coefficient.png")


"""
Scatter plot of the centrality and ingress traffic args.visualization_timestamp_s seconds
"""
fig, ax = plt.subplots(1, 1)
ax.scatter(
    [
        i[0]
        for i in combined_centrality_ingress[
            int(
                args.visualization_timestamp_s
                / (interval_s * args.averaging_over_timestamps_n)
            )
        ]
    ],
    [
        i[1]
        for i in combined_centrality_ingress[
            int(
                args.visualization_timestamp_s
                / (interval_s * args.averaging_over_timestamps_n)
            )
        ]
    ],
)
ax.set_xlabel("Ingress Traffic Amount")
ax.set_ylabel("Topological Centrality")
ax.set_title(f"Ingress vs Centrality at {args.visualization_timestamp_s} s")
plt.savefig("ingress_centrality.png")
