from scipy.stats import spearmanr
import json
import numpy as np
import argparse

"""
In order to get the correct results from this script, you need to include GSL results in your scripts.
To do this, un-comment the block quote in `parse_ingress_traffic_by_satellite.py` and generate a separate
ingress traffic file to use with this script.

ingress_with_gs_filename: the previously generated file
centrality_filename: the filename for the betweenness centrality file you want to check,
generated by `parse_betweenness_centrality.py`
num_satellites: the number of satellites being tested
"""

parser = argparse.ArgumentParser()
parser.add_argument("ingress_with_gs_filename")
parser.add_argument("centrality_filename")
parser.add_argument("num_satellites", type=int)
args = parser.parse_args()

ingress_list = np.zeros(args.num_satellites)
centrality_list = np.zeros(args.num_satellites)

with open(args.ingress_filename) as f:
    all_time = json.load(f)
    """ this is inelegant but can be easily fixed in the future: change the key here to be the time you want to check in units of 100ms.
    For example, for the default Hypatia settings, this can be anything from 0-1999, representing 0-199.9s """
    moment = all_time["0"]
    for key in moment.keys():
        ingress_list[int(key)] = int(moment[key])

with open(args.centrality_filename) as f:
    moment = json.load(f)
    for key in moment.keys():
        centrality_list[int(key)] = int(moment[key])

rho, p = spearmanr(ingress_list, centrality_list)
print(rho, p)
